league: premier_league
sources:
  - name: guardian_football
    url: https://www.theguardian.com/football/rss
  - name: bbc_football
    url: http://feeds.bbci.co.uk/sport/football/rss.xml
  - name: sky_sports_premier_league
    url: https://www.skysports.com/rss/12040
  - name: independent_football
    url: https://www.independent.co.uk/sport/football/rss
timeout_s: 15
