# config/feeds.yaml
league: premier_league
sources:
  - name: guardian_football
    url: https://www.theguardian.com/football/rss
  - name: bbc_football
    url: http://feeds.bbci.co.uk/sport/football/rss.xml
timeout_s: 15
