name: build_and_push
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Az login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az acr login --name afpacr

      - name: Build & push
        run: |
          IMAGE=afpacr.azurecr.io/afp-runner
          TAG=latest
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG
