name: Build and Deploy Produce Job

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ secrets.ACR_NAME }}
          containerAppName: afp-produce
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.ACR_NAME }}.azurecr.io/afp-produce:${{ github.sha }}
          dockerfilePath: ./Dockerfile

      - name: Update Azure Container Apps Job
        run: |
          az containerapp job update \
            --name afp-produce \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/afp-produce:${{ github.sha }}
