name: Deploy AFP Jobs

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id:        ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
          subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ===============================
      #   Set secrets in Azure Jobs
      # ===============================

      # afp-collect-job → JOB_TYPE=collect
      - name: Set SAS secret (collect)
        run: az containerapp job secret set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-collect-job --secrets BLOB_CONTAINER_SAS_URL="${{ secrets.BLOB_CONTAINER_SAS_URL }}"

      # afp-produce-job → JOB_TYPE=produce
      - name: Set SAS secret (produce)
        run: az containerapp job secret set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-produce-job --secrets BLOB_CONTAINER_SAS_URL="${{ secrets.BLOB_CONTAINER_SAS_URL }}"

      # afp-assemble-job → JOB_TYPE=assemble
      - name: Set SAS secret (assemble)
        run: az containerapp job secret set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-assemble-job --secrets BLOB_CONTAINER_SAS_URL="${{ secrets.BLOB_CONTAINER_SAS_URL }}"

      # ===============================
      #   Update job definitions
      # ===============================

      # afp-collect-job → JOB_TYPE=collect
      - name: Update collect job
        run: az containerapp job update --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-collect-job --yaml .github/workflows/collect-job.yaml

      # afp-produce-job → JOB_TYPE=produce
      - name: Update produce job
        run: az containerapp job update --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-produce-job --yaml .github/workflows/produce-job.yaml

      # afp-assemble-job → JOB_TYPE=assemble
      - name: Update assemble job
        run: az containerapp job update --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name afp-assemble-job --yaml .github/workflows/assemble-job.yaml
