name: Opinion Section (AK/JJK)

on:
  workflow_dispatch:
    inputs:
      speaker:
        description: "AK or JJK"
        required: true
        default: "AK"
      news_path:
        description: "Path to news input (txt/md)"
        required: true
        default: "inputs/sample_news.md"
      personas_path:
        description: "Path to personas.json"
        required: true
        default: "config/personas.json"
      model:
        description: "OpenAI model (default gpt-4o-mini)"
        required: false
        default: "gpt-4o-mini"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate opinion
        env:
          AFP_OPENAI_SECRETKEY: ${{ secrets.AFP_OPENAI_SECRETKEY }}
          OPENAI_MODEL: ${{ github.event.inputs.model }}
        run: |
          python scripts/generate_opinion.py \
            --speaker "${{ github.event.inputs.speaker }}" \
            --news "${{ github.event.inputs.news_path }}" \
            --personas "${{ github.event.inputs.personas_path }}" \
            --outdir "outputs/sections"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opinion_section_${{ github.event.inputs.speaker }}
          path: outputs/sections/
