# produce-job.yaml
name: afp-produce-job
type: Microsoft.App/jobs
location: westeurope

properties:
  configuration:
    triggerType: Manual

  template:
    containers:
      - name: afp
        image: afpacr.azurecr.io/afp-runner:gh-PLACEHOLDER
        env:
          - name: JOB_TYPE
            value: produce
          - name: SECTION_ID
            value: S.NEWS.TOPN   # default, kan skrivas över i Actions
          - name: FEEDS
            value: guardian_football,bbc_football,sky_sports_premier_league,independent_football
          - name: TOP_N
            value: "3"
          - name: LEAGUE
            value: premier_league
          - name: DAY
            value: "2025-08-28"  # default, Actions kan skriva över
          - name: LANG
            value: en
        resources:
          cpu: 0.5
          memory: "1Gi"
