apiVersion: 2023-05-01
kind: Job
location: westeurope
name: afp-produce-job
type: Microsoft.App/jobs
properties:
  configuration:
    triggerType: Manual
    replicaTimeout: 1800
    replicaRetryLimit: 1
    manualTriggerConfig:
      parallelism: 1
      completions: 1
  template:
    containers:
      - name: afp-produce-job
        image: afpacr.azurecr.io/afp-runner:latest
        command: ["python"]
        args: ["-m", "src.sections.s_news_top3_guardian"]
        env:
          - name: AZURE_STORAGE_ACCOUNT
            value: afpstoragepilot
          - name: AZURE_CONTAINER
            value: afp
    scale:
      minExecutions: 0
      maxExecutions: 1
