name: afp-produce-job
type: Microsoft.App/jobs
location: westeurope

properties:
  configuration:
    triggerType: Manual
  template:
    containers:
      - name: afp
        image: afpacr.azurecr.io/afp-runner:latest
        env:
          - name: JOB_TYPE
            value: producer
          - name: BLOB_PREFIX
            value: "producer/"
          - name: BLOB_CONTAINER_SAS_URL
            secretRef: BLOB_CONTAINER_SAS_URL
          # - name: JOB_ARGS
          #   value: "--limit 12"
