name: afp-producer
type: Microsoft.App/jobs
location: westeurope

properties:
  configuration:
    triggerType: Manual
    secrets:
      - name: BLOB_CONTAINER_SAS_URL
        value: "https://afpstoragepilot.blob.core.windows.net/afp?sp=rcwl&st=2025-08-18T06:07:15Z&se=2025-09-30T14:22:15Z&spr=https&sv=2024-11-04&sr=c&sig=eXkVRxRs%2ByTXVlNGq5%2BF2at3uYf4EyCZvjE3jlWaN54%3D"

  template:
    containers:
      - name: afp
        image: afpacr.azurecr.io/afp-runner:latest
        env:
          - name: JOB_TYPE
            value: producer
          - name: BLOB_PREFIX
            value: "producer/"
          - name: BLOB_CONTAINER_SAS_URL
            secretRef: BLOB_CONTAINER_SAS_URL
          # Exempel på extra modulargument (ta bort om inte behövs)
          # - name: JOB_ARGS
          #   value: "--limit 12"
