jobs:
- name: afp-produce
  type: job
  properties:
    configuration:
      image: <ACR_OR_DOCKERHUB_IMAGE_TAG>
      env:
        - name: JOB_TYPE
          value: "produce"
        - name: JOB_ARGS
          # Exempel: kör expertkommentaren (JJK) på Arsenal
          value: "--section-code S.OPINION.EXPERT_COMMENT --news inputs/sample_news.md --league premier_league --topic arsenal --write-latest"
        - name: AFP_OPENAI_SECRETKEY
          secretRef: afp-openai-secret
        - name: BLOB_CONTAINER_SAS_URL
          secretRef: afp-sas-url
    scale:
      minExecutions: 0
      maxExecutions: 1
