name: rss-smoke

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install PyYAML tidigt för sanity-extraktion
      - name: Install PyYAML (for sanity check)
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Extract RSS URLs from config/feeds.yaml
        id: extract_urls
        run: |
          python - <<'PY'
          import yaml, sys
          with open("config/feeds.yaml", "r", encoding="utf-8") as f:
              cfg = yaml.safe_load(f)
          urls = [s["url"] for s in cfg.get("sources", []) if "url" in s]
          with open("urls.txt", "w", encoding="utf-8") as f:
              for u in urls:
                  f.write(u.strip() + "\n")
          print(f"Found {len(urls)} URL(s).")
          PY

      # Tolerant sanity-check: följer redirects, har retry och varnar istället för att faila direkt.
      - name: Sanity check RSS endpoints (HEAD, tolerant)
        run: |
          set -euo pipefail
          fails=0
          while IFS= read -r u; do
            echo "Checking: $u"
            if ! curl -sSIL -L --max-time 12 --retry 2 --retry-all-errors -A "afp-rss-smoke/1.0" "$u" | head -n 1; then
              echo "::warning::Sanity check failed for $u"
              fails=$((fails+1))
            fi
          done < urls.txt
          # Tillåt 1 fel utan att stoppa jobbet
          if [ "$fails" -gt 1 ]; then
            echo "::error::Too many failed feeds ($fails)."
            exit 1
          fi

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run collector in LOCAL mode
        env:
          STORAGE_MODE: local
          LOCAL_OUT_DIR: _out
        run: python -m src.collectors.rss_multi

      - name: Run top3 in LOCAL mode
        env:
          STORAGE_MODE: local
          LOCAL_OUT_DIR: _out
          LEAGUE: premier_league
        run: python -m src.sections.s_news_top3_generic

      - name: Upload artifact (_out)
        uses: actions/upload-artifact@v4
        with:
          name: rss-smoke-out
          path: _out/
