name: Run Produce Job

on:
  workflow_dispatch:

jobs:
  produce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}



      - name: Select subscription
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # Här sätter vi env-variabler på jobben innan det startas
      - name: Update env vars for Produce job
        run: |
          # fallback till dagens datum om inget anges
          DAY=$(date -u +"%Y-%m-%d")
          az containerapp job update \
            --name afp-produce-job \
            --resource-group afp-rg \
            --set-env-vars \
              SECTION_ID="S.NEWS.TOPN" \
              FEEDS="guardian_football,bbc_football,sky_sports_premier_league,independent_football" \
              TOP_N="3" \
              LEAGUE="premier_league" \
              DAY="$DAY" \
              LANG="en"

      - name: Start job
        run: |
          az containerapp job start \
            --name afp-produce-job \
            --resource-group afp-rg
